name: Coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Cover
      run: go test -v ./... -covermode=count -coverprofile=coverage.out

    - name: Report
      run: go tool cover -func=coverage.out -o=coverage.out


